#!/bin/bash

# spotify_announce_tracks
# 
# This script sits in the background and announces Spotify track changes via text-to-speech
# 
# (c) Glutanimate 2014 <https://github.com/Glutanimate/>
# License: GNU GPLv3
# 
# Dependencies: xdotool x11-utils simple-google-tts spotify
#
# NOTICE:         THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW. 
#                 EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES 
#                 PROVIDE THE PROGRAM “AS IS” WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR 
#                 IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY 
#                 AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND 
#                 PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE,
#                 YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.
#
#                 IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING WILL ANY 
#                 COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS THE PROGRAM AS 
#                 PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, 
#                 INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE 
#                 THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED 
#                 INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE OF THE 
#                 PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH HOLDER OR OTHER 
#                 PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.


# Variables

TTSEngine="simple_google_tts en" # Modify this to change the TTS command.
                                 # Uses simple-google-tts by default:
                                 # (https://github.com/Glutanimate/simple-google-tts)

WmTitle="Spotify (Premium |Unlimited )?- Linux Preview"

# Functions

change_spotify_volume(){
  for i in {1..5}; do
    sleep 0.1
    xdotool key --window "$SpotifyWindow" "ctrl+$1"
  done
}

# Main

SpotifyWindow="$(xdotool search --name "$WmTitle" 2> /dev/null | head -n1)"

if [[ -z "$SpotifyWindow" ]]; then
  echo "Spotify not found"
  exit 1
fi

xprop -spy -name "$WmTitle" WM_ICON_NAME | \
  while read -r XpropOut; do

      TrackInfo="$(echo "$XpropOut" \
       | cut -d\" -f 2- | rev | cut -d\" -f 2- | rev | cut -d "-" -f2)"

      if [[ "$TrackInfo" = " Spotify – Spotify" || "$TrackInfo" = "Spotify" ]]; then
        TrackInfo="Ad intermission"
        # continue
      fi

      echo "$TrackInfo"
      sleep 2
      change_spotify_volume "Down"
      $TTSEngine "$TrackInfo" > /dev/null 2>&1
      change_spotify_volume "Up"

  done